% -----------------------
% DEFINE FOLDER LOCATIONS
path_final_tables = '../draft/final tables/';
path_raw_mapdata = '../data';
datafolder_ne = [path_raw_mapdata,'/NaturalEarth/'];
datafolder_DIVA = [path_raw_mapdata,'/DIVA/'];
datafolder_Eurogeog_old = [path_raw_mapdata,'/Euroglobal/EGM_8-0SHP_20151028/DATA/Countries/'];
datafolder_Eurogeog = datafolder_Eurogeog_old;
datafolder_Eurogeog_Europe_old = [path_raw_mapdata,'/Euroglobal/EGM_8-0SHP_20151028/DATA/FullEurope/'];
datafolder_Eurogeog_Europe  = datafolder_Eurogeog_Europe_old;
datafolder_SEDAC = [path_raw_mapdata,'/SEDAC/gpw-v4-population-count-adjusted-to-2015-unwpp-country-totals-2005/'];  
datafolder_gecon = [path_raw_mapdata,'/G-Econ/'];
datafolder_ETOPO = [path_raw_mapdata,'/ETOPO/'];
datafolder_nuts1 = [path_raw_mapdata,'/NUTS/NUTS_RG_01M_2016_4326_LEVL_1.shp/'];
datafolder_nuts2 = [path_raw_mapdata,'/NUTS/NUTS_RG_01M_2016_4326_LEVL_2.shp/'];
datafolder_nuts3 = [path_raw_mapdata,'/NUTS/NUTS_RG_01M_2016_4326_LEVL_3.shp/'];
datafolder_spain_trade = [path_raw_mapdata,'/Spain/trade/'];
path_save_grids = './country grids/';
path_save_grids_country_bounds = './country grids/country_bounds/';
path_load_grids = './country grids/';
path_load_cfactuals = './country grids/cfactuals/'; 
path_save_cfactuals = './country grids/cfactuals/';
path_save_calibrations = './country grids/calibrations/';
path_save_tables = './country grids/tables_dtilde/';
path_save_plots = './country grids/grid_plots/';
path_save_cfactual_plots = './country grids/cfactuals/plots/maps/';
path_save_cfactual_plots_europe = './country grids/cfactuals/plots/maps/europe/';
path_save_summary_tables = './country grids/summary_tables/';
path_save_cfactuals_plots = './country grids/cfactuals/plots/';
path_save_cfactuals_plots_welfare = './country grids/cfactuals/plots/reallocation_welfare/';
datafolder_connected_countries = './connected_countries_data/';
path_gravity = './country grids/gravity/';  
datafolder_traveltimes = [path_raw_mapdata,'/travel_times/'];
path_papers_graph = '../draft/final tables/';  

% take care of portability across platforms
folder_list = {'path_final_tables',...
               'path_raw_mapdata',...
               'datafolder_ne',...
               'datafolder_DIVA',...
               'datafolder_Eurogeog',...
               'datafolder_Eurogeog_old',...
               'datafolder_Eurogeog_Europe',...
               'datafolder_SEDAC',...
               'datafolder_gecon',...
               'datafolder_ETOPO',...
               'datafolder_nuts1',...
               'datafolder_nuts2',...
               'datafolder_nuts3',...
               'datafolder_spain_trade',...
               'path_save_grids',...
               'path_load_grids',...
               'path_save_grids_country_bounds',...
               'path_load_cfactuals',...
               'path_save_cfactuals',...
               'path_save_calibrations',...
               'path_save_tables',...
               'path_save_plots',...
               'path_save_cfactuals_plots',...
               'path_save_summary_tables',...
               'path_save_cfactuals_plots',...
               'path_save_cfactual_plots_europe',...
               'path_save_cfactuals_plots_welfare',...
               'datafolder_connected_countries',...
               'path_gravity',...
               'datafolder_traveltimes',...
               'path_papers_graph'};
           
if ispc() == true % if running on PC Windows    
    for k=1:length(folder_list) % for all folders, substitute '/' with '\'
        cmd = sprintf('%s = strrep(%s,''/'',''\\'');',folder_list{k},folder_list{k}); 
        eval(cmd); 
    end
end