function out = rdfilter_connected(icc)

connected = {'AT','AT#CH','AT#DE','AT#IT',...
             'BE','BE#DE','BE#FR','BE#LU','BE#NL',...
             'CH','CH#FR','CH#IT',...
             'DE','DE#FR','DE#NL','DE#DK','DE#LU',...
             'DK',...
             'ES','ES#FR','ES#PT',...
             'FR','FR#MC','FR#LU',...
             'IT','IT#SM',...
             'LU',...
             'MC',...
             'NL',...
             'PT',...
             'SM' };

out = 'false';   
for i=1:length(connected)
    out = strcmp(icc,connected(i));
    if out, break,end
end